config/routes.rb
Rails.application.routes.draw do
  resources :transactions

  root 'transactions#index'

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
    geocoded_by :address
    # auto-fetch coordinates and the condition is for preventing fetching the same address more than once
    after_validation :geocode, if: :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:district, :target, :address, :area, :city_usage, :noncity_usage, :noncity_control, :transaction_date, :num_transaction_land, :num_transaction_build, :num_transaction_park, :floor, :total_floors, :usage, :material, :built_date, :transaction_build_area, :num_room, :num_hall, :num_bath, :barrier, :management, :price, :price_per_area, :park_type, :transaction_park_area, :park_price, :comment, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Real Estate Transactions</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyDaiHpfdztF_SN_O4UnOTPOPZlMiyp1JWI" type="text/javascript"></script>
    <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :target %><br>
    <%= f.text_field :target %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :city_usage %><br>
    <%= f.text_field :city_usage %>
  </div>
  <div class="field">
    <%= f.label :noncity_usage %><br>
    <%= f.text_field :noncity_usage %>
  </div>
  <div class="field">
    <%= f.label :noncity_control %><br>
    <%= f.text_field :noncity_control %>
  </div>
  <div class="field">
    <%= f.label :transaction_date %><br>
    <%= f.date_select :transaction_date %>
  </div>
  <div class="field">
    <%= f.label :num_transaction_land %><br>
    <%= f.number_field :num_transaction_land %>
  </div>
  <div class="field">
    <%= f.label :num_transaction_build %><br>
    <%= f.number_field :num_transaction_build %>
  </div>
  <div class="field">
    <%= f.label :num_transaction_park %><br>
    <%= f.number_field :num_transaction_park %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.number_field :floor %>
  </div>
  <div class="field">
    <%= f.label :total_floors %><br>
    <%= f.text_field :total_floors %>
  </div>
  <div class="field">
    <%= f.label :usage %><br>
    <%= f.text_field :usage %>
  </div>
  <div class="field">
    <%= f.label :material %><br>
    <%= f.text_field :material %>
  </div>
  <div class="field">
    <%= f.label :built_date %><br>
    <%= f.date_select :built_date %>
  </div>
  <div class="field">
    <%= f.label :transaction_build_area %><br>
    <%= f.text_field :transaction_build_area %>
  </div>
  <div class="field">
    <%= f.label :num_room %><br>
    <%= f.number_field :num_room %>
  </div>
  <div class="field">
    <%= f.label :num_hall %><br>
    <%= f.number_field :num_hall %>
  </div>
  <div class="field">
    <%= f.label :num_bath %><br>
    <%= f.number_field :num_bath %>
  </div>
  <div class="field">
    <%= f.label :barrier %><br>
    <%= f.check_box :barrier %>
  </div>
  <div class="field">
    <%= f.label :management %><br>
    <%= f.check_box :management %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :price_per_area %><br>
    <%= f.text_field :price_per_area %>
  </div>
  <div class="field">
    <%= f.label :park_type %><br>
    <%= f.text_field :park_type %>
  </div>
  <div class="field">
    <%= f.label :transaction_park_area %><br>
    <%= f.text_field :transaction_park_area %>
  </div>
  <div class="field">
    <%= f.label :park_price %><br>
    <%= f.text_field :park_price %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<div class="left">
    <div class="ui-state-error-text ui-corner-all">
        <strong>選擇縣市:</strong>
        <form>
            <select name="location">
                <option value="Taichung">台中</option>
            </select>
        </form>
        <div id="counting"></div>
    </div>
    <div class="clear">&nbsp;</div>
    <div class="ui-state-error-text ui-corner-all">
        <strong>Filter by Price:</strong>
        <span id="currentRange"></span>
        <div id="slider"></div>
    </div>
    <div class="clear">&nbsp;</div>
    <div class="ui-state-error-text ui-corner-all">
        <strong>Zoom Level:</strong>
        <input id="spinner" value="8" readonly="readonly"/>
    </div>
    <div class="clear">&nbsp;</div>
    <div id="listing">
    </div>
</div>
<div class="right" id="map-container">
        <div id="map-canvas">
        </div>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>District:</strong>
  <%= @transaction.district %>
</p>

<p>
  <strong>Target:</strong>
  <%= @transaction.target %>
</p>

<p>
  <strong>Address:</strong>
  <%= @transaction.address %>
</p>

<p>
  <strong>Area:</strong>
  <%= @transaction.area %>
</p>

<p>
  <strong>City usage:</strong>
  <%= @transaction.city_usage %>
</p>

<p>
  <strong>Noncity usage:</strong>
  <%= @transaction.noncity_usage %>
</p>

<p>
  <strong>Noncity control:</strong>
  <%= @transaction.noncity_control %>
</p>

<p>
  <strong>Transaction date:</strong>
  <%= @transaction.transaction_date %>
</p>

<p>
  <strong>Num transaction land:</strong>
  <%= @transaction.num_transaction_land %>
</p>

<p>
  <strong>Num transaction build:</strong>
  <%= @transaction.num_transaction_build %>
</p>

<p>
  <strong>Num transaction park:</strong>
  <%= @transaction.num_transaction_park %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @transaction.floor %>
</p>

<p>
  <strong>Total floors:</strong>
  <%= @transaction.total_floors %>
</p>

<p>
  <strong>Usage:</strong>
  <%= @transaction.usage %>
</p>

<p>
  <strong>Material:</strong>
  <%= @transaction.material %>
</p>

<p>
  <strong>Built date:</strong>
  <%= @transaction.built_date %>
</p>

<p>
  <strong>Transaction build area:</strong>
  <%= @transaction.transaction_build_area %>
</p>

<p>
  <strong>Num room:</strong>
  <%= @transaction.num_room %>
</p>

<p>
  <strong>Num hall:</strong>
  <%= @transaction.num_hall %>
</p>

<p>
  <strong>Num bath:</strong>
  <%= @transaction.num_bath %>
</p>

<p>
  <strong>Barrier:</strong>
  <%= @transaction.barrier %>
</p>

<p>
  <strong>Management:</strong>
  <%= @transaction.management %>
</p>

<p>
  <strong>Price:</strong>
  <%= @transaction.price %>
</p>

<p>
  <strong>Price per area:</strong>
  <%= @transaction.price_per_area %>
</p>

<p>
  <strong>Park type:</strong>
  <%= @transaction.park_type %>
</p>

<p>
  <strong>Transaction park area:</strong>
  <%= @transaction.transaction_park_area %>
</p>

<p>
  <strong>Park price:</strong>
  <%= @transaction.park_price %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @transaction.comment %>
</p>

<p>
  <strong>Id:</strong>
  <%= @transaction.id %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>